[package]
name = "r_texture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
image = "0.23"
ndarray = "0.15"
ndarray-rand = "0.14.0"
ndarray-npy = "0.8.1"
rand = "0.8"
glob = "0.3"
